name: Deploy to Appetize

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuração do Node.js (se necessário)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Ou a versão que você está utilizando

      # 3. Instalação de dependências
      - name: Install dependencies
        run: npm install # Substitua se necessário

      # 4. Construção do app
      - name: Build the app (Android APK ou iOS IPA)
        run: |
          npm run android # Comando para gerar o APK, caso seja React Native, ajuste conforme seu projeto
          # Ou se for para iOS: npm run ios

      # 5. Fazer o upload do APK para o Appetize
      - name: Upload APK to Appetize
        uses: appetizeio/appetize-action@v1.0.0
        with:
          api_key: ${{ secrets.APPETIZE_API_KEY }} # Sua chave API do Appetize (adicionada nos GitHub Secrets)
          file_path: ./android/app/build/outputs/apk/release/app-release.apk # Caminho para o arquivo APK gerado
          platform: android # Ou "ios" se você estiver usando iOS
          wait_for_processing: true # Aguarda o processamento do upload

      # 6. Exibir URL do Appetize
      - name: Display Appetize URL
        run: |
          echo "Appetize URL: https://appetize.io/app/${{ steps.upload.outputs.appetize_url }}"
