name: Deploy to Appetize

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      # Instalação do Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-toolchain@v2
        with:
          api-level: 30 # Você pode ajustar para a versão desejada do Android
          target: android-30
          arch: x86_64 # Você pode ajustar para o tipo de arquitetura do seu projeto
          force: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      # Instalação de dependências
      - name: Install dependencies
        run: npm install

      # Construção do app (APK ou iOS)
      - name: Build the app (Android APK ou iOS IPA)
        run: |
          npm run android # Ou npm run ios se for iOS

      # Upload do APK para o Appetize
      - name: Upload APK to Appetize
        uses: appetizeio/github-action-appetize@v1.0.3
        with:
          api_key: ${{ secrets.APPETIZE_API_KEY }}
          file_path: ./android/app/build/outputs/apk/release/app-release.apk
          platform: android
          wait_for_processing: true

      # Exibir URL do Appetize
      - name: Display Appetize URL
        run: |
          echo "Appetize URL: https://appetize.io/app/${{ steps.upload.outputs.appetize_url }}"
