name: Deploy to Appetize

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      # Instalação de dependências
      - name: Install dependencies
        run: npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
      - name: Delete Android build duplicate assets resource
        run: yarn run delete-pics
      - name: Install bundler
        run: |
          cd android
          gem install bundler
      - name: Install gem plugins
        run: |
          cd android
          bundle install

      # Upload do APK para o Appetize
      - name: Upload APK to Appetize
        uses: appetizeio/github-action-appetize@v1.0.3
        with:
          api_key: ${{ secrets.APPETIZE_API_KEY }}
          file_path: ./android/app/build/outputs/apk/release/app-release.apk
          platform: android
          wait_for_processing: true

      # Exibir URL do Appetize
      - name: Display Appetize URL
        run: |
          echo "Appetize URL: https://appetize.io/app/${{ steps.upload.outputs.appetize_url }}"
