name: Deploy to Appetize

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Instalar Expo CLI (novo)
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Build do app para Android (APK)
      - name: Build the app (Android APK)
        run: |
          expo build:android -t apk --no-publish

      # Obter o caminho do APK gerado
      - name: Get the APK file
        run: |
          APK_PATH=$(ls ./dist/*.apk)
          echo "APK path: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      # Upload do APK para Appetize
      - name: Upload APK to Appetize
        uses: appetizeio/github-action-appetize@v1.0.3
        with:
          api_key: ${{ secrets.APPETIZE_API_KEY }} # Chave de API do Appetize
          file_path: ${{ env.APK_PATH }} # Caminho do APK
          platform: android # Ou "ios" se for iOS
          wait_for_processing: true # Espera o processamento do upload

      # Exibir a URL do Appetize
      - name: Display Appetize URL
        run: |
          echo "Appetize URL: https://appetize.io/app/${{ steps.upload.outputs.appetize_url }}"
