name: Deploy to Appetize

on:
  pull_request:
    branches:
      - master # ou a branch que você deseja usar como base para PRs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      # 1. Configuração do Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 2. Instalação de dependências
      - name: Install dependencies
        run: npm install

      # 3. Instalação do Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-8-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d android-sdk
          sudo mv android-sdk /usr/local/android-sdk
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      # 4. Construção do app (APK para Android)
      - name: Build the app (Android APK)
        run: |
          npm run android

      # 5. Fazer o upload do APK para o Appetize
      - name: Upload APK to Appetize
        uses: appetizeio/github-action-appetize@v1.0.3
        with:
          api_key: ${{ secrets.APPETIZE_API_KEY }} # Sua chave API do Appetize (adicionada nos GitHub Secrets)
          file_path: ./android/app/build/outputs/apk/release/app-release.apk # Caminho para o arquivo APK gerado
          platform: android # Ou "ios" se você estiver usando iOS
          wait_for_processing: true # Aguarda o processamento do upload

      # 6. Exibir URL do Appetize
      - name: Display Appetize URL
        run: |
          echo "Appetize URL: https://appetize.io/app/${{ steps.upload.outputs.appetize_url }}"
